# Generated by Django 5.1.4 on 2025-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('origin', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('measurements', models.CharField(max_length=100)),
                ('carat_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=50)),
                ('clarity', models.CharField(max_length=50)),
                ('cut', models.CharField(max_length=50)),
                ('proportions', models.CharField(max_length=100)),
                ('polish', models.CharField(max_length=50)),
                ('symmetry', models.CharField(max_length=50)),
                ('fluorescence', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('price_range', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('in_progress', 'Đang định giá'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
