# Generated by Django 5.1.4 on 2025-02-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationrequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
